[package]
name = "gloss"
version = "0.1.0"
authors = ["rheber <rheber@rediffmail.com>"]

[dependencies]
clap = "2.26"
hyper = "0.11"
reqwest = "0.7"
serde_json = "1.0"

[[bin]]
name = "gloss"
doc = false
